### ISSUE TITLE
Empty  builder.Salary

### ISSUE THREAD

**Issue by mmisu** [mhdbouk/AutoBuilder#1]
// result
Hello, World!
{"Id":1,"Name":"John","Address":"123 Main St","Jajo":["test"],"Orders":[{"Product":"Shoes","Price":50},{"Product":"Shirt","Price":25}],"Ignored":0,"Salary":{"Amount":0,"Currency":""}}

**Comment by mhdbouk** [comment]
Thanks for pointing out that, it was a failed experiment 😅 I will remove that and work on it in a separated branch

**Comment by mhdbouk** [comment]
@mmisu thank you for pointing it out, it is now fixed. this is the new output
```

Hello, World!
{"Id":1,"Name":"John","Address":"123 Main St","Orders":[{"Product":"Shoes","Price":50},{"Product":"Shirt","Price":25}],"Ignored":0,"Salary":{"Amount":200,"Currency":"USD"}}

New builder from existing object
{"Id":1,"Name":"John","Address":"123 Main St","Orders":[{"Product":"Shoes","Price":50},{"Product":"Shirt","Price":25},{"Product":"Socks","Price":5}],"Ignored":0,"Salary":{"Amount":200,"Currency":"USD"}}

```

**Comment by mmisu** [comment]
Thanks a lot.
